title: Page
pages: true
files: 
  sortable: true
fields:
  title:
    label: Titre
    type:  text
	exergue:
		label: Exergue
		type: textarea
		buttons: false
  text:
    label: Texte
    type:  wysiwyg